# Global parameters
c: 0.2 # Penalty parameter
num_runs: 5 # Number of runs per instance
num_workers: null # Number of parallel workers (null = auto-detect)

# Interior Point method configuration
InteriorPoint:
  max_iter: 1000
  tol: 1e-8
  verbose: 0

# Manifold method configuration
Manifold:
  optimizer: "steepest_descent" # Options: "steepest_descent", "trust_regions", "conjugate_gradient"
  max_iter: 500
  verbose: 0

# OT4P method configuration
OT4P4AS:
  max_iter: 3000
  initial_tau: 0.7
  final_tau: 0.5
  annealing_scheme: "exponential" # Options: "exponential", "linear", "cosine"
  decay_steps: 5000
  learning_rate: 0.1
  min_rel_improvement: 1e-4
  verbose: 0

# QSA method configuration
QSA:
  max_iter: 500
  tol: 1e-8
  verbose: 0

# SoftSort method configuration
SoftSort:
  max_iter: 2000
  initial_tau: 1.0
  final_tau: 1e-6
  annealing_scheme: "cosine"
  learning_rate: 0.1
  min_rel_improvement: 1e-4
  verbose: 0
